#!/bin/bash
set -e

echo "Standardrb $(bundle exec standardrb --version)"
bundle exec standardrb --fix "$@"
success=$?
if ((success != 0)); then
   echo -e "\nTry running \`script/fmt -a\` to automatically fix errors"
fi
exit $success
